gate-issue: Update tests to use fake clients
IndexError: list index out of range errors are seen while
executing py27 jobs as tests try to connect to real client
instead of fake ones while polling. This commit fixes the same.

Closes-Bug:#1648320
Change-Id: Ieb42e8265a6ada95a3430a3f78a01806f714be0e