Resolve instability in json_ingester test_execute_exec_api_rows
Occassionally the unit test congress.tests.datasources.json_ingester.
test_exec_api.TestExecApiManager.test_execute_exec_api_rows
fails inside eventlet code even though the eventlet call is mocked
out.

This patch adds a new mock path because eventlet.spawn_n
somehow redirects there. Hopefully it resolves the occassional
instability gets.

Sample error:
  File "/home/zuul/src/git.openstack.org/openstack/congress/.tox/py27/local/lib/python2.7/site-packages/eventlet/greenpool.py", line 115, in spawn_n
    function, args, kwargs, True)
  File "/home/zuul/src/git.openstack.org/openstack/congress/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/home/zuul/src/git.openstack.org/openstack/congress/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 1128, in _mock_call
    ret_val = effect(*args, **kwargs)
  File "congress/tests/datasources/json_ingester/test_exec_api.py", line 27, in mock_spawn_execute
    return func(*args, **kwargs)
  File "/home/zuul/src/git.openstack.org/openstack/congress/.tox/py27/local/lib/python2.7/site-packages/eventlet/greenpool.py", line 99, in _spawn_n_impl
    self._spawn_done(coro)
  File "/home/zuul/src/git.openstack.org/openstack/congress/.tox/py27/local/lib/python2.7/site-packages/eventlet/greenpool.py", line 131, in _spawn_done
    self.coroutines_running.remove(coro)
KeyError: <greenlet.greenlet object at 0x7fd975681cd0>

Change-Id: I72e11a67cf1cd3ff3fbc574f2d6e91df17d63d9c