Use only strings in paste.deploy.loadapp global_conf
1. encode the flags as json
2. pass node_id, bus_id rather than DseNode instance.
   Create DseNode in harness not eventlet_server.

Rationale: global_conf not meant to take non-strings.
Somehow got away with it in python2, but fails in python3.

When dict (and DseNode) passed through global_conf,
paste.deploy.loadapp adds them to configparser defaults,
causing errors when configparser calls string methods on them.

File "/usr/lib/python3.4/configparser.py",
    line 390, in _interpolate_some
    p = rest.find("%")
AttributeError:
    Error in file congress/tests/etc/api-paste.ini:
    'dict' object has no attribute 'find'

Change-Id: I549b9281e72512bb804a7d6f07bf6482e9485ae4